#!/bin/bash

## before run.. add a tag
## git tag -f -a "v0.2.0-2.1.4"  -m "Upgrade to haproxy 2.1.4 and stdout logging output"
##
build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
version=$(git describe --tags 2> /dev/null || echo "$SOURCE_BRANCH")
vcs_ref=$(git rev-parse --short HEAD)

docker build \
  --build-arg BUILD_DATE="$build_date"  \
  --build-arg VCS_REF="$vcs_ref"        \
  --build-arg VERSION="$version"        \
  -t "$IMAGE_NAME:latest" \
  -t "$IMAGE_NAME:$version" .
